version: "2"
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.7
    restart: unless-stopped
    depends_on:
      - "es01"
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: '["http://es01:9200"]'
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: changeme
    networks:
      - demo
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.7
    environment:
      - node.name
      - cluster.name
      - discovery.seed_hosts
      - cluster.initial_master_nodes
      - bootstrap.memory_lock
      - ES_JAVA_OPTS
      - xpack.security.enabled
      - xpack.security.authc.api_key.enabled
      - ELASTIC_PASSWORD
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    networks:
      - demo
  mariadb:
    image: mariadb:10.2
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: mybb
      MYSQL_USER: mybb
      MYSQL_PASSWORD: changeme
    networks:
      - demo
    expose:
      - 3306
    restart: on-failure
  keycloak:
    build: keycloak_auth
    environment:
      - KEYCLOAK_ADMIN
      - KEYCLOAK_ADMIN_PASSWORD
      - KC_DB
      - KC_DB_URL_HOST
      - KC_DB_URL_DATABASE
      - KC_DB_URL_PORT
      - KC_DB_USERNAME
      - KC_DB_PASSWORD
      - KC_HOSTNAME
      - KC_HOSTNAME_STRICT_HTTPS
      - KC_HTTP_ENABLED
      - KC_PROXY
    expose:
      - 8443
      - 8080
    networks:
      - demo
  frontend:
    networks:
      - demo
    build: frontend
    expose:
      - 80
  es-search:
    expose:
      - 80
    networks:
      - demo
    build: es-service
networks:
    demo:
      external:
          name: demo